server:
  port: ${PORT:8880}
  servlet:
    context-path: /api/v1/library
    
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/libraryDB


#Nos configurations
mes-configs.limitDeProduits: 4